# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import PIL
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from Library import *
import resources_rc


class BookWidget (QtWidgets.QWidget):
    def __init__ (self, parent = None, book = None):
        super(BookWidget, self).__init__(parent)
        self.com = True
        self.fav = True
        self.textQVBoxLayout = QtWidgets.QVBoxLayout()
        self.textTitle = QtWidgets.QLabel()
        self.textAuthor = QtWidgets.QLabel()
        self.textQVBoxLayout.addWidget(self.textTitle)
        self.textQVBoxLayout.addWidget(self.textAuthor)
        self.allQHBoxLayout = QtWidgets.QHBoxLayout()
        self.iconQLabel = QtWidgets.QLabel()
        self.iconQLabel.setMaximumSize(QtCore.QSize(80, 120))
        self.iconQLabel.setScaledContents(True)
        self.frame = QtWidgets.QFrame()
        self.frame.setMaximumSize(QtCore.QSize(60, 500))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.comQLabel = QtWidgets.QLabel(self.frame)
        self.favQLabel = QtWidgets.QLabel(self.frame)
        self.comQLabel.setPixmap(QtGui.QPixmap(":/icons/mark.png"))
        self.favQLabel.setPixmap(QtGui.QPixmap(":/icons/heart.png"))
        self.favQLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.comQLabel)
        self.horizontalLayout.addWidget(self.favQLabel)
        self.allQHBoxLayout.addWidget(self.iconQLabel, 0)
        self.allQHBoxLayout.addLayout(self.textQVBoxLayout, 1)
        self.allQHBoxLayout.addWidget(self.frame, 2)
        self.setLayout(self.allQHBoxLayout)
        
        
        self.textTitle.setStyleSheet('''
            font-size:18pt;
        ''')
        self.textAuthor.setStyleSheet('''
            font-size:18pt;
            color: rgb(54, 54, 54);
        ''')
        
        self.toggleCom()
        self.toggleFav()
        self.update(book)

    def setTitle (self, text):
        self.textTitle.setText(text)

    def setAuthor (self, text):
        self.textAuthor.setText(text)
    
    def toggleCom(self):
        self.comQLabel.setHidden(self.com)
        self.com = not self.com
        
    def toggleFav(self):
        self.favQLabel.setHidden(self.fav)
        self.fav = not self.fav

    def update(self, book):
        if book:
            self.setTitle(book.title)
            self.setAuthor(book.author)
            self.favQLabel.setHidden(book.favourite)
            self.comQLabel.setHidden(book.complete)
            #TODO update icon
    
    def setIconFromPath (self, imagePath):
        self.iconQLabel.setPixmap(QtGui.QPixmap(imagePath))
        
    def setIconFromBytes (self, data):
        if data is None:
            return
        if not isinstance(data, bytes):
            data = bytes(data, encoding='utf8')
        pixmap = QtGui.QPixmap()
        pixmap.loadFromData(data)
        self.iconQLabel.setPixmap(pixmap)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 132)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonOk = self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok)
        self.buttonCancel = self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonOk.setText('OK')
        self.buttonCancel.setText('Anuluj')
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.rejected)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Podaj nową nazwę"))
        self.label.setText(_translate("Dialog", "Nazwa"))
        

class RenameDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)
        self.change = True
    
    def inputValue(self):
        return self.ui.lineEdit.text()
        
    def rejected(self):
        self.change = False
        self.reject()
    

    



